version: "3.7"

services:
  web:
    build: ./test_django
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - test_django/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=db_admin
      - POSTGRES_DB=dbo
    ports:
      - 5432:5432

volumes:
  postgres_data: